<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Quadra.Workers.Background-208999f7-53bf-4cfc-9f68-78c33188cd3b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.32" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quadra.Shared\Quadra.Shared.csproj" />
    <ProjectReference Include="..\Quadra.Infrastructure\Quadra.Infrastructure.csproj" />
    <ProjectReference Include="..\Quadra.Modules.Profile\Quadra.Modules.Profile.csproj" />
    <ProjectReference Include="..\Quadra.Modules.Matches\Quadra.Modules.Matches.csproj" />
    <ProjectReference Include="..\Quadra.Modules.InGame\Quadra.Modules.InGame.csproj" />
    <ProjectReference Include="..\Quadra.Modules.Gamification\Quadra.Modules.Gamification.csproj" />
  </ItemGroup>
</Project>
