// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quadra.Modules.InGame.Persistence;

#nullable disable

namespace Quadra.Modules.InGame.Migrations
{
    [DbContext(typeof(InGameDbContext))]
    [Migration("20260702171656_CreateScoreboardTables")]
    partial class CreateScoreboardTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quadra.Modules.InGame.Entities.Scoreboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("CurrentSetNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("current_set_number");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("state");

                    b.Property<Guid>("TeamAId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_a_id");

                    b.Property<short>("TeamASetsWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("team_a_sets_won");

                    b.Property<Guid>("TeamBId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_b_id");

                    b.Property<short>("TeamBSetsWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("team_b_sets_won");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("uq_scoreboards_match_id");

                    b.ToTable("scoreboards", (string)null);
                });

            modelBuilder.Entity("Quadra.Modules.InGame.Entities.ScoreboardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("IsDecidingSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deciding_set");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("ScoreboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoreboard_id");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("InProgress")
                        .HasColumnName("status");

                    b.Property<short>("TeamAPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("team_a_points");

                    b.Property<short>("TeamBPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("team_b_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_scoreboard_sets_match_id");

                    b.HasIndex("ScoreboardId")
                        .HasDatabaseName("ix_scoreboard_sets_scoreboard_id");

                    b.HasIndex("ScoreboardId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_scoreboard_sets_scoreboard_set_number");

                    b.ToTable("scoreboard_sets", (string)null);
                });

            modelBuilder.Entity("Quadra.Modules.InGame.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_teams_match_id");

                    b.HasIndex("MatchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_teams_match_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Quadra.Modules.InGame.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_team_members_match_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_members_team_id");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("uq_team_members_match_player");

                    b.ToTable("team_members", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
